services:

  comfyui:
    init: true
    container_name: comfyui
    build:
      context: .
      dockerfile: Dockerfile
    image: "minozar/1of10-comfyui-pipelines:latest"
    ports:
      - "8188:8188"
    volumes:
      - "./models:/root/ComfyUI/models"
    environment:
      - CLI_ARGS=
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
